name: PHPCpdAction
description: Run your PHP Copy Paste Detector in your Github Actions.

inputs:
  path:
    description: A php source code filename or directory. Can be a comma-separated string
    required: true

  exclude:
    description: comma-separated string of patterns that are used to ignore directories. Use asterisks to exclude by pattern. For example *src/foo/*.php or *src/foo/*
    required: false

runs:
  using: "composite"
  steps:
    - env:
        ACTION_PATH: ${{ inputs.path }}
        ACTION_EXCLUDE: ${{ inputs.exclude }}

      id: phpcpd_run
      run: |
        set -e
        bash ${{ github.action_path }}/phpcpd-action.bash
      shell: bash

branding:
  icon: 'check-square'
  color: 'purple'
